"""phase2: marking schemes, components, marks entries

Revision ID: 09c0a67e354c
Revises: 539d8fc20f00
Create Date: 2026-07-05 19:08:18.895639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c0a67e354c'
down_revision: Union[str, Sequence[str], None] = '539d8fc20f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marking_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marking_schemes_id'), 'marking_schemes', ['id'], unique=False)
    op.create_table('scheme_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('min_marks', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['marking_schemes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_component_scheme_code')
    )
    op.create_index(op.f('ix_scheme_components_id'), 'scheme_components', ['id'], unique=False)
    op.create_index(op.f('ix_scheme_components_scheme_id'), 'scheme_components', ['scheme_id'], unique=False)
    op.create_table('marks_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['scheme_components.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'component_id', name='uq_mark_student_course_component')
    )
    op.create_index(op.f('ix_marks_entries_component_id'), 'marks_entries', ['component_id'], unique=False)
    op.create_index(op.f('ix_marks_entries_course_id'), 'marks_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_marks_entries_id'), 'marks_entries', ['id'], unique=False)
    op.create_index(op.f('ix_marks_entries_student_id'), 'marks_entries', ['student_id'], unique=False)
    op.create_foreign_key(None, 'users', 'divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_marks_entries_student_id'), table_name='marks_entries')
    op.drop_index(op.f('ix_marks_entries_id'), table_name='marks_entries')
    op.drop_index(op.f('ix_marks_entries_course_id'), table_name='marks_entries')
    op.drop_index(op.f('ix_marks_entries_component_id'), table_name='marks_entries')
    op.drop_table('marks_entries')
    op.drop_index(op.f('ix_scheme_components_scheme_id'), table_name='scheme_components')
    op.drop_index(op.f('ix_scheme_components_id'), table_name='scheme_components')
    op.drop_table('scheme_components')
    op.drop_index(op.f('ix_marking_schemes_id'), table_name='marking_schemes')
    op.drop_table('marking_schemes')
    # ### end Alembic commands ###
