"""create mentor_assignments table

Revision ID: 28cd897e98f7
Revises: 178c0cb2368a
Create Date: 2026-06-29 15:59:06.584102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cd897e98f7'
down_revision: Union[str, Sequence[str], None] = '178c0cb2368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_assignments_id'), 'mentor_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_assignments_student_id'), 'mentor_assignments', ['student_id'], unique=True)
    op.create_index(op.f('ix_mentor_assignments_teacher_id'), 'mentor_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentor_assignments_teacher_id'), table_name='mentor_assignments')
    op.drop_index(op.f('ix_mentor_assignments_student_id'), table_name='mentor_assignments')
    op.drop_index(op.f('ix_mentor_assignments_id'), table_name='mentor_assignments')
    op.drop_table('mentor_assignments')
    # ### end Alembic commands ###
