"""phase3: teacher branch_id, student mentor_id, subject_teachers table

Revision ID: 7f0a2d1fee44
Revises: f830d0d864ba
Create Date: 2026-07-06 11:36:52.979631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0a2d1fee44'
down_revision: Union[str, Sequence[str], None] = 'f830d0d864ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'course_id', 'division_id', name='uq_subject_teacher')
    )
    op.create_index(op.f('ix_subject_teachers_course_id'), 'subject_teachers', ['course_id'], unique=False)
    op.create_index(op.f('ix_subject_teachers_division_id'), 'subject_teachers', ['division_id'], unique=False)
    op.create_index(op.f('ix_subject_teachers_id'), 'subject_teachers', ['id'], unique=False)
    op.create_index(op.f('ix_subject_teachers_teacher_id'), 'subject_teachers', ['teacher_id'], unique=False)
    op.add_column('users', sa.Column('branch_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('mentor_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_mentor_id'), 'users', ['mentor_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['mentor_id'], ['id'])
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_mentor_id'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_column('users', 'mentor_id')
    op.drop_column('users', 'branch_id')
    op.drop_index(op.f('ix_subject_teachers_teacher_id'), table_name='subject_teachers')
    op.drop_index(op.f('ix_subject_teachers_id'), table_name='subject_teachers')
    op.drop_index(op.f('ix_subject_teachers_division_id'), table_name='subject_teachers')
    op.drop_index(op.f('ix_subject_teachers_course_id'), table_name='subject_teachers')
    op.drop_table('subject_teachers')
    # ### end Alembic commands ###
