"""create guidance_cases table

Revision ID: 8e85fc8a96d9
Revises: 0c64b64045a1
Create Date: 2026-06-29 16:42:39.634577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e85fc8a96d9'
down_revision: Union[str, Sequence[str], None] = '0c64b64045a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidance_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('owning_teacher_id', sa.String(length=36), nullable=True),
    sa.Column('trigger_signal', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('date_opened', sa.Date(), nullable=True),
    sa.Column('date_resolved', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owning_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidance_cases_id'), 'guidance_cases', ['id'], unique=False)
    op.create_index(op.f('ix_guidance_cases_owning_teacher_id'), 'guidance_cases', ['owning_teacher_id'], unique=False)
    op.create_index(op.f('ix_guidance_cases_student_id'), 'guidance_cases', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guidance_cases_student_id'), table_name='guidance_cases')
    op.drop_index(op.f('ix_guidance_cases_owning_teacher_id'), table_name='guidance_cases')
    op.drop_index(op.f('ix_guidance_cases_id'), table_name='guidance_cases')
    op.drop_table('guidance_cases')
    # ### end Alembic commands ###
