"""add academic_year and batch to users, add cohorts table

Revision ID: 9d632766a453
Revises: cd5c1c471429
Create Date: 2026-07-02 09:53:18.147603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d632766a453'
down_revision: Union[str, Sequence[str], None] = 'cd5c1c471429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'department', name='uq_cohort_year_dept')
    )
    op.create_index(op.f('ix_cohorts_id'), 'cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_cohorts_mentor_id'), 'cohorts', ['mentor_id'], unique=False)
    op.add_column('users', sa.Column('academic_year', sa.String(), nullable=True))
    op.add_column('users', sa.Column('batch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'batch')
    op.drop_column('users', 'academic_year')
    op.drop_index(op.f('ix_cohorts_mentor_id'), table_name='cohorts')
    op.drop_index(op.f('ix_cohorts_id'), table_name='cohorts')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
