"""add domain_interest to profiles

Revision ID: cd5c1c471429
Revises: 8e85fc8a96d9
Create Date: 2026-06-30 20:49:43.178543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5c1c471429'
down_revision: Union[str, Sequence[str], None] = '8e85fc8a96d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('domain_interest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'domain_interest')
    # ### end Alembic commands ###
