"""phase6: audit log, co-curricular, best-5 subjects, experience fields

Revision ID: d7148f635d08
Revises: 1da9e1bd080f
Create Date: 2026-07-06 18:07:41.563884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7148f635d08'
down_revision: Union[str, Sequence[str], None] = '1da9e1bd080f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('co_curriculars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organisation', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_curriculars_id'), 'co_curriculars', ['id'], unique=False)
    op.create_index(op.f('ix_co_curriculars_user_id'), 'co_curriculars', ['user_id'], unique=False)
    op.add_column('experiences', sa.Column('is_paid', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('supervisor_contact', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('faculty_guide', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('work_model', sa.String(), nullable=True))
    op.add_column('experiences', sa.Column('reflection', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('best_five_subjects', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'best_five_subjects')
    op.drop_column('experiences', 'reflection')
    op.drop_column('experiences', 'work_model')
    op.drop_column('experiences', 'faculty_guide')
    op.drop_column('experiences', 'supervisor_contact')
    op.drop_column('experiences', 'is_paid')
    op.drop_index(op.f('ix_co_curriculars_user_id'), table_name='co_curriculars')
    op.drop_index(op.f('ix_co_curriculars_id'), table_name='co_curriculars')
    op.drop_table('co_curriculars')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
