"""create skills_master table

Revision ID: dff2105e3d3a
Revises: 43a7fe232175
Create Date: 2026-07-05 18:11:17.327630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff2105e3d3a'
down_revision: Union[str, Sequence[str], None] = '43a7fe232175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name', name='uq_skillsmaster_domain_name')
    )
    op.create_index(op.f('ix_skills_master_domain_id'), 'skills_master', ['domain_id'], unique=False)
    op.create_index(op.f('ix_skills_master_id'), 'skills_master', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_master_id'), table_name='skills_master')
    op.drop_index(op.f('ix_skills_master_domain_id'), table_name='skills_master')
    op.drop_table('skills_master')
    # ### end Alembic commands ###
