"""create private_notes table

Revision ID: eb8af14a29f6
Revises: 28cd897e98f7
Create Date: 2026-06-29 16:10:35.721925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8af14a29f6'
down_revision: Union[str, Sequence[str], None] = '28cd897e98f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_notes_id'), 'private_notes', ['id'], unique=False)
    op.create_index(op.f('ix_private_notes_student_id'), 'private_notes', ['student_id'], unique=False)
    op.create_index(op.f('ix_private_notes_teacher_id'), 'private_notes', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_private_notes_teacher_id'), table_name='private_notes')
    op.drop_index(op.f('ix_private_notes_student_id'), table_name='private_notes')
    op.drop_index(op.f('ix_private_notes_id'), table_name='private_notes')
    op.drop_table('private_notes')
    # ### end Alembic commands ###
