"""phase2: add marking_scheme_id FK to courses

Revision ID: f830d0d864ba
Revises: 09c0a67e354c
Create Date: 2026-07-05 19:19:40.392114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f830d0d864ba'
down_revision: Union[str, Sequence[str], None] = '09c0a67e354c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('marking_scheme_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_courses_marking_scheme_id'), 'courses', ['marking_scheme_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'marking_schemes', ['marking_scheme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_marking_scheme_id'), table_name='courses')
    op.drop_column('courses', 'marking_scheme_id')
    # ### end Alembic commands ###
